name: Publish to NPM and GitHub Packages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        registry: [ 'https://registry.npmjs.org/', 'https://npm.pkg.github.com/' ]
        include:
          - token_secret: 'NPM_TOKEN'
            registry: 'https://registry.npmjs.org/'
          - token_secret: 'GITHUB_TOKEN'
            registry: 'https://npm.pkg.github.com/'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: ${{ matrix.registry }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.token_secret] }}
